- hosts: my_servers
  become: true
  gather_facts: false
  tasks:
    - name: Copy archive
      copy:
        src: "versions/web_static_20230710040523.tgz"
        dest: "/tmp/"

    - name: Extract archive
      command: "tar -xzf /tmp/web_static_20230710040523.tgz -C /data/web_static/releases/"

    - name: Copy index.html to current folder
      copy:
        src: "path_to_index_files/0-index.html"
        dest: "/data/web_static/current/"

    - name: Copy index.html to release folder
      copy:
        src: "path_to_index_files/0-index.html"
        dest: "/data/web_static/releases/web_static_20230710040523.tgz/"

    - name: Update symbolic link
      file:
        src: "/data/web_static/releases/web_static_20230710040523.tgz"
        dest: "/data/web_static/current"
        state: link
        force: yes
